---
# tasks for vbotka.freebsd-postinstall

- import_tasks: debug.yml
  when: fp_debug
  tags: fp_debug

- import_tasks: loader.yml
  tags: fp_loader

- import_tasks: sysctl.yml
  tags: fp_sysctl

- import_tasks: make.yml
  tags: fp_make

- import_tasks: swap.yml
  tags: fp_swap

- import_tasks: fstab.yml
  tags: fp_fstab

- import_tasks: packages.yml
  tags: fp_packages

- import_tasks: copy.yml
  tags: fp_copy

- import_tasks: libmap.yml
  tags: fp_libmap

- import_tasks: users.yml
  tags: fp_users

- import_tasks: groupwrappers.yml
  tags: fp_groupwrappers
  when: fp_groupwrappers_install

- import_tasks: hostname.yml
  tags: fp_hostname

- import_tasks: hosts.yml
  tags: fp_hosts

- import_tasks: ssh.yml
  tags: fp_ssh

- import_tasks: authorized_key.yml
  tags: fp_authorized_key

- import_tasks: timezone.yml
  tags: fp_timezone

- import_tasks: ntpd.yml
  tags: fp_ntpd

- import_tasks: ntpdate.yml
  tags: fp_ntpdate

- import_tasks: nfs.yml
  tags: fp_nfs

- import_tasks: nfsd.yml
  tags: fp_nfsd

- import_tasks: smartd.yml
  tags: fp_smartd
  when: fp_smartd_install

- import_tasks: apcupsd.yml
  tags: fp_apcupsd

- import_tasks: hostapd.yml
  tags: fp_hostapd
  when: fp_hostapd_install

- import_tasks: procmail.yml
  tags: fp_procmail
  when: fp_procmail_install

- import_tasks: motd.yml
  tags: fp_motd

- import_tasks: gitserver.yml
  tags: fp_gitserver
  when: fp_gitserver_install

- import_tasks: sudoers.yml
  tags: fp_sudoers

- import_tasks: cron.yml
  tags: fp_cron

- import_tasks: resolvconf.yml
  tags: fp_resolvconf

# EOF
...
