---

- name: "sudoers: Configure {{ fp_sudoers_conf_file }}"
  ansible.builtin.lineinfile:
    dest: "{{ fp_sudoers_conf_file }}"
    regexp: '^\s*{{ item.key }}\s+(.*)$'
    line: "{{ item.key }} {{ item.value }}"
    state: "{{ item.state|default(omit) }}"
    insertafter: EOF
    owner: "{{ fp_sudoers_conf_owner }}"
    group: "{{ fp_sudoers_conf_group }}"
    mode: "{{ fp_sudoers_conf_mode }}"
    backup: "{{ fp_backup }}"
  loop: "{{ fp_sudoers_conf }}"

# TODO:
# (1) configure /usr/local/etc/sudoers.d
# (2) configure /usr/local/etc/sudoers.dist

# EOF
...
